### PR TITLE
Wdp210702 9 Add global hover transitions

### PR DESCRIPTION
**Pull request by AnOlbr**
The goal of this task was to implement global variables of transition time.

They've been written in file settings.scss and added in entire project, wherever :hover effect occures.

### CODE REVIEW

**Comment by Varenthein** [comment]
Please add a description to the PR. You should cover "What was the goal of the task" and "how I've done it".

**Comment by Varenthein** [comment]
Why in the commits list of this PR you have commits from other tasks? :O You've probably started a new task from a branch of an older task instead of a master. Never do that! Always start a new branch for the new task from the master branch.

If not, you ask for undesired conflicts :)

I don't ask you to this branch again but remember about this for new tasks. For now, just fix conflicts and we're good to go.

**Comment by AnOlbr** [comment]
> Why in the commits list of this PR you have commits from other tasks? :O You've probably started a new task from a branch of an older task instead of a master. Never do that! Always start a new branch for the new task from the master branch.
> 

To pewnie mam tak wszędzie do tej pory, nie sądziłam, że to tak działa, że robię branch brancha, przechodząc do nowego taska :(

**Comment by Varenthein** [comment]
> > Why in the commits list of this PR you have commits from other tasks? :O You've probably started a new task from a branch of an older task instead of a master. Never do that! Always start a new branch for the new task from the master branch.
> 
> To pewnie mam tak wszędzie do tej pory, nie sądziłam, że to tak działa, że robię branch brancha, przechodząc do nowego taska :(

Niestety tak. Jak tworzysz nowy branch z innego brancha, to ten nowy startuje z cala zawartoscią tego starego wlasnie. Twoje szczescie, ze te taski, ktore wykonywalas nie mialy bugów ;) W przeciwnym razie byłoby sporo zabawy z konfliktami. Niemniej jednak na przyszłosć pamięaj – nowy branch dla nowego tasku zawsze twórz z poziomu mastera.

**Comment by Varenthein** [comment]
Please resolve conflicts

**Pull request merged**
