### PR TITLE
Wdp210702 6 Add old price

### PR DESCRIPTION
**Pull request by AnOlbr**
The goal of this task was to add old, crossed out prices around actual prices of choosen products.

I've added a new variable to const ProductBox - "oldPrice", which renders in desired place. However, old prices are stored in initialState, where may have a value or just be empty. Needed scsses are written.

### CODE REVIEW

**Review by deidrah — APPROVED** [review]

**Comment by Varenthein** [comment]
Please add a description to the PR. You should cover "What was the goal of the task" and "how I've done it".

**Comment by Varenthein** [comment]
Please resolve conflicts

**Comment by Varenthein** [comment]
There are still conflicts to resolve.

**Comment by deidrah** [comment]
I resolved them

**Pull request merged**
